services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    ports:
      - "27017:27017"
    volumes:
      - ./database/init-mongo.js.template:/docker-entrypoint-initdb.d/init-mongo.js.template:ro
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - retail_network

  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    environment:
      MONGO_URL: mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@database:27017/${DATABASE_NAME}
    depends_on:
      - database
    networks:
      - retail_network

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - back
    networks:
      - retail_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - database
    networks:
      - retail_network

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: llm
    ports:
      - "5001:5001"
    volumes:
      - ./llm:/app
      - llm_models:/app/models
    environment:
      FASTAPI_URL: "http://back:8000/api"
    networks:
      - retail_network
    depends_on:
      - back
    stdin_open: true
    tty: true

networks:
  retail_network:
    driver: bridge

volumes:
  mongo_data:
  llm_models:
